/*

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function (s, t) {
    let arr = Array(26).fill(0);
    let aCharCode = 'a'.charCodeAt(0);

    [...t].forEach(ch => arr[ch.charCodeAt(0) - aCharCode]++);
    [...s].forEach(ch => arr[ch.charCodeAt(0) - aCharCode]--);

    for (let i = 0; i < arr.length; i++) {
        if (arr[i] == 1) return String.fromCharCode(aCharCode + i);
    }

    return "";
};

console.log(findTheDifference("abcd", "abcde"));